version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/find_a_mate_app
    docker:
      - image: circleci/ruby:2.7.2-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install

  test:
    parallelism: 3
    docker:
      - image: circleci/postgres:13.2
    steps:
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:8080 -timeout 1m
      - run:
          name: Setup DB
          command: bundle exec rails db:create db:schema:load --trace
      # Run rspec in parallel
      - ruby/rspec-test
      - ruby/rubocop-check
